---
title: "Committee Report"
author: "Rebecca Howard"
date: "10/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(maps)
library(mapdata)
library(fields)
library(plotfunctions)
library(mgcv)
library(dplyr)
library(plyr)

setwd('/Users/howar/Documents/Oregon State/ORnearshore_groundfish/code')
trawl_data <- read.delim('../data/NMFS_data/trawl_data.txt')
OR_fish <- read.delim('../data/NMFS_data/OR_fish.txt')
load('../data/bathy.dat')
load('../data/bathy.mat')
```

To prepare the figures for the manuscript submission, I've been finding ways to speed up my old code
I first did this with creating species subsets, by writing a function to do it for me
```{r}
subset_species <- function(species, catch, tows){
  OR_subset <- catch[catch$scientific_name == species, ]
  match_id <- match(tows$trawl_id, OR_subset$trawl_id)
  tows$lncpue <- OR_subset$lncpue_n[match_id]
  tows$lncpue[is.na(tows$lncpue)] <- 0
  selected_species <- select(tows, julian, year, lncpue, latitude, longitude, bottom_temp, depth_m)
  selected_species <- na.omit(selected_species)
  selected_species$pres <- 1 * (selected_species$lncpue > 0)
  return(selected_species)
}

# Eight species of interest
arrowtooth_subset <- subset_species("Atheresthes stomias", OR_fish, trawl_data)
english_subset <- subset_species("Parophrys vetulus", OR_fish, trawl_data)
sanddab_subset <- subset_species("Citharichthys sordidus", OR_fish, trawl_data)
dover_subset <- subset_species("Microstomus pacificus", OR_fish, trawl_data)
rex_subset <- subset_species("Glyptocephalus zachirus", OR_fish, trawl_data)
lingcod_subset <- subset_species("Ophiodon elongatus", OR_fish, trawl_data)
petrale_subset <- subset_species("Eopsetta jordani", OR_fish, trawl_data)
sablefish_subset <- subset_species("Anoplopoma fimbria", OR_fish, trawl_data)
```


I'm also working on improving the quality of the thesis figures.

```{r}
gam<-gam(lncpue~s(year, k = 5)+s(longitude,latitude) + s(depth_m) + s(julian, k = 5) + 
             s(bottom_temp, k = 5),data=rex_subset[rex_subset$lncpue>0,])
plot(gam,
  pages = 0,
  select = 1,
  shade = T,
  main = "Year",
  xlab = "",
  ylab = "",
  seWithMean = T,
  scale = 0,
  cex.axis = 1.5,
  cex.main = 2)
plot(gam,
  pages = 0,
  select = 3,
  shade = T,
  main = "Depth",
  xlab = "",
  ylab = "",
  seWithMean = T,
  scale = 0,
  cex.axis = 1.5,
  cex.main = 2)
plot(gam,
  pages = 0,
  select = 4,
  shade = T,
  main = "Day of Year",
  xlab = "",
  ylab = "",
  seWithMean = T,
  scale = 0,
  cex.axis = 1.5,
  cex.main = 2)
plot(gam,
  pages = 0,
  select = 5,
  shade = T,
  main = "Temperature",
  xlab = "",
  ylab = "",
  seWithMean = T,
  scale = 0,
  cex.axis = 1.5,
  cex.main = 2)
```

